### ISSUE TITLE
NJOEntropy logic

### ISSUE THREAD

**Issue by peterbartos** [jasonnam/Navajo-Swift#3]
It looks that your NJOEntropy logic is different than the original logic from the mattt/Navajo project. 

You are increasing the sizeOfCharacterSet by 26 by every lower-case character, meanwhile the original project only once, on first lower-case character.

Is this change on purpose?

**Comment by jasonnam** [comment]
Hey Peter! Thank you for pointing out that issue. This is not intended and very serious issue. I just pushed update and sorry for your inconveniences.
This is why we work together! Thanks again.
