### ISSUE TITLE
Swift 5 broken because "static" declarations are implicitly final.

### ISSUE THREAD

**Issue by SuperTango** [jasonnam/Navajo-Swift#5]
In Swift 5, "static" declarations are implicitly final as per error message.  The error is: 

    static declarations are implicitly 'final'; use 'public' instead of 'open' 

4 places need to be updated.

**Comment by SuperTango** [comment]
Pull request https://github.com/jasonnam/Navajo-Swift/pull/4 created

**Comment by jasonnam** [comment]
Thank you for the pull request. I am going to prepare Swift 5 support soon!

**Comment by netgfx** [comment]
is this also updated for cocoapods as well? Because after pod-install I'm still getting the error. thanks! @jasonnam

**Comment by nickmshelley** [comment]
I'm just pointing my Podfile to master for now, but it would be great if there was an official cocoapods release that works with Swift 5.

**Comment by jasonnam** [comment]
Pushed to CocoaPods!
